version: "3.8"
services:
  knoteContainer:
    image: knote-java
    ports:
    - "8080:8080"
    networks:
      - knote
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.6
    networks:
      - knote
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=per

networks:
  knote:

